language: node_js
sudo: false
node_js:
  - "10"
jobs:
  include:
    - language: node_js
      node_js: 10
      before_install:
        - npm install -g grunt-cli
        - gem install bundler
        - cd analysis && bundle install
      script:
        - npm install && npm test
    - language: node_js
      node_js: 10
      before_install:
        - cd web-sourcecode
      script:
        - npm install && npm run test:unit
notifications:
  email:
    - casden@gmail.com
    - bddavids@ncsu.edu
    - kdbeswic@ncsu.edu
    - lmaeschl@ncsu.edu
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a200c25b0cbac74e2b9e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
matrix:
  allow_failures:
    - node_js: "5"
